//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaborStackApp.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaborStackApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 appEmployee/addEmployees 的本地化字符串。
        /// </summary>
        internal static string AddEmployees {
            get {
                return ResourceManager.GetString("AddEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 appTeam/add 的本地化字符串。
        /// </summary>
        internal static string AddTeam {
            get {
                return ResourceManager.GetString("AddTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 appPersonnel/addWorkers 的本地化字符串。
        /// </summary>
        internal static string AddWorkers {
            get {
                return ResourceManager.GetString("AddWorkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读卡异常 的本地化字符串。
        /// </summary>
        internal static string CARD_READ_EXCEPTION {
            get {
                return ResourceManager.GetString("CARD_READ_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读卡失败 的本地化字符串。
        /// </summary>
        internal static string CARD_READ_FAILURE {
            get {
                return ResourceManager.GetString("CARD_READ_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到读卡设备 的本地化字符串。
        /// </summary>
        internal static string CARD_READ_NOTFOUND {
            get {
                return ResourceManager.GetString("CARD_READ_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读卡成功 的本地化字符串。
        /// </summary>
        internal static string CARD_READ_SUCCEED {
            get {
                return ResourceManager.GetString("CARD_READ_SUCCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 appEmployee/delete 的本地化字符串。
        /// </summary>
        internal static string DeleteEmployee {
            get {
                return ResourceManager.GetString("DeleteEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 appTeam/delete 的本地化字符串。
        /// </summary>
        internal static string DeleteTeam {
            get {
                return ResourceManager.GetString("DeleteTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 appPersonnel/deleteSingle 的本地化字符串。
        /// </summary>
        internal static string DeleteWorker {
            get {
                return ResourceManager.GetString("DeleteWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 v116/appPersonnel/v116GetAppWorkerMasterByProjectCode 的本地化字符串。
        /// </summary>
        internal static string GetAppWorkerMasterByProjectCode {
            get {
                return ResourceManager.GetString("GetAppWorkerMasterByProjectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 v116/appProject/v116GetProjectsByCompany 的本地化字符串。
        /// </summary>
        internal static string GetProjectsByCompany {
            get {
                return ResourceManager.GetString("GetProjectsByCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 appTeam/getTeamsByProjectCode 的本地化字符串。
        /// </summary>
        internal static string GetTeamsByProjectCode {
            get {
                return ResourceManager.GetString("GetTeamsByProjectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 appEmployee/selectEmployeesByProjectCode 的本地化字符串。
        /// </summary>
        internal static string SelectEmployeesByProjectCode {
            get {
                return ResourceManager.GetString("SelectEmployeesByProjectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://hnsq.jsxywg.cn 的本地化字符串。
        /// </summary>
        internal static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 appTeam/update 的本地化字符串。
        /// </summary>
        internal static string UpdateTeam {
            get {
                return ResourceManager.GetString("UpdateTeam", resourceCulture);
            }
        }
    }
}
